/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#4cd7f6',
        'surface-bright': '#31394d',
        'inverse-surface': '#dae2fd',
        'on-error-container': '#ffdad6',
        'on-tertiary-container': '#3d4042',
        'secondary-fixed': '#acedff',
        'surface-tint': '#4ae176',
        'inverse-on-surface': '#283044',
        error: '#ffb4ab',
        'primary-fixed-dim': '#4ae176',
        'surface-variant': '#2d3449',
        'surface-dim': '#0b1326',
        'on-surface-variant': '#bccbb9',
        'on-primary-fixed': '#002109',
        'surface-container-lowest': '#060e20',
        secondary: '#4cd7f6',
        'on-secondary': '#003640',
        primary: '#4be277',
        background: '#0b1326',
        'on-tertiary-fixed': '#191c1e',
        'on-primary-fixed-variant': '#005321',
        'on-primary': '#003915',
        'on-surface': '#dae2fd',
        'on-error': '#690005',
        'on-tertiary': '#2d3133',
        surface: '#0b1326',
        'on-secondary-fixed-variant': '#004e5c',
        'tertiary-fixed': '#e0e3e5',
        'on-secondary-fixed': '#001f26',
        'surface-container-high': '#222a3d',
        'secondary-container': '#03b5d3',
        'outline-variant': '#3d4a3d',
        'on-tertiary-fixed-variant': '#444749',
        tertiary: '#c5c7c9',
        'error-container': '#93000a',
        'on-primary-container': '#004b1e',
        'inverse-primary': '#006e2f',
        'on-background': '#dae2fd',
        'tertiary-container': '#a9acae',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-container-highest': '#2d3449',
        'on-secondary-container': '#00424e',
        'primary-container': '#22c55e',
        'primary-fixed': '#6bff8f',
        'surface-container-low': '#131b2e',
        outline: '#869585',
        'surface-container': '#171f33',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        'margin-mobile': '16px',
        gutter: '16px',
        xl: '32px',
        base: '4px',
        md: '16px',
        sm: '12px',
        xs: '8px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'data-label': ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'data-label': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      animation: {
        scroll: 'scroll 20s linear infinite',
        marquee: 'marquee 40s linear infinite',
        'bg-pan': 'bg-pan 3s linear infinite',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        scroll: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        marquee: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'bg-pan': {
          '0%': { backgroundPosition: '100% 0' },
          '100%': { backgroundPosition: '-100% 0' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(74, 225, 118, 0.4)' },
          '50%': { opacity: '0.8', transform: 'scale(1.02)', boxShadow: '0 0 10px 4px rgba(74, 225, 118, 0)' },
        },
      },
    },
  },
  plugins: [],
};
